-- STEP 2: tables + security. Everyone can read, only admins (see 1-admins.sql) can write.
create table if not exists public.players (
  id bigint generated by default as identity primary key,
  name text not null unique
);
create table if not exists public.tournaments (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null default 'tournament' check (type in ('tournament','social','manual')),
  date text not null default '',
  entries jsonb not null default '[]'::jsonb
);
alter table public.players enable row level security;
alter table public.tournaments enable row level security;

drop policy if exists "read players" on public.players;
drop policy if exists "admin write players" on public.players;
drop policy if exists "read tournaments" on public.tournaments;
drop policy if exists "admin write tournaments" on public.tournaments;
create policy "read players" on public.players for select using (true);
create policy "admin write players" on public.players for all to authenticated using (public.is_admin()) with check (public.is_admin());
create policy "read tournaments" on public.tournaments for select using (true);
create policy "admin write tournaments" on public.tournaments for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- holds the + / - quick point adjustments
insert into public.tournaments (id, name, type) values (0, 'Manual adjustments', 'manual') on conflict (id) do nothing;

-- live updates for visitors (run once; ignore the error if it says already member)
alter publication supabase_realtime add table public.players, public.tournaments;
