-- STEP 3 (optional): imports your current players and tournaments.
insert into public.players (name) values
  ('Abdullah Ali'),
  ('Abdullah Salim'),
  ('Asad Al Touqi'),
  ('Azzan Al Said'),
  ('Badar Al ghafri'),
  ('Bassam Al Shaidhani'),
  ('Jaber Al Harthy'),
  ('Laith Al Harthy'),
  ('Lutfy Al Oweiny'),
  ('Manaf Al-Barwani'),
  ('Mohammed Al Balushi'),
  ('Mohd Alhajri'),
  ('Mohd Alkhaifi'),
  ('Muayad Ambusaidi'),
  ('Muhanned Ambusaidi'),
  ('Nader Al Qassmi'),
  ('Salim Al Falahi'),
  ('Sami Al abdulsalam'),
  ('Sami Al-busaidi'),
  ('Talal Busaidi'),
  ('Wael Al Barwani'),
  ('Wael Ambusaidi'),
  ('Yazan Ambusaidi'),
  ('Yussuf Al-Harthy'),
  ('Hilal Al Jabri'),
  ('Ali Al Hajri'),
  ('Faisal Al Ghailani'),
  ('Ahmed Al Riyami'),
  ('Haitham Al Riyami'),
  ('Musab Al Siyabi'),
  ('Ammar'),
  ('Humood Al Adawi'),
  ('Khaled Al Harthy'),
  ('Mohd Barwani'),
  ('Hamdi Al Mawali'),
  ('Ahmed Al Azri'),
  ('Samer'),
  ('Mohsin Al Battashi'),
  ('Nasser Al Hajri'),
  ('Salim AL Hajri'),
  ('Usama Al Mawali'),
  ('Abdul Malik Al Balushi'),
  ('Amir'),
  ('Mohammed Al Asmi'),
  ('Asaad Al Dhuhli'),
  ('Sultan B'),
  ('Mohammed Saud'),
  ('Marwan'),
  ('Sultan Al Harthy'),
  ('Haitham'),
  ('Sulaiman'),
  ('Yussuf Al Barwani')
on conflict (name) do nothing;

insert into public.tournaments (name, type, date, entries) values
  ('Tournament 1','tournament','','[{"n": "Abdullah Ali", "p": 4}, {"n": "Abdullah Salim", "p": 20}, {"n": "Asad Al Touqi", "p": 6}, {"n": "Manaf Al-Barwani", "p": 1}, {"n": "Mohammed Al Balushi", "p": 10}, {"n": "Mohd Alhajri", "p": 2}, {"n": "Muayad Ambusaidi", "p": 10}, {"n": "Nader Al Qassmi", "p": 1}, {"n": "Sami Al abdulsalam", "p": 1}, {"n": "Sami Al-busaidi", "p": 2}, {"n": "Talal Busaidi", "p": 2}, {"n": "Wael Al Barwani", "p": 2}, {"n": "Wael Ambusaidi", "p": 8}, {"n": "Yazan Ambusaidi", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 20}, {"n": "Sultan Al Harthy", "p": 4}]'::jsonb),
  ('Mexicano 1','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Abdullah Salim", "p": 4}, {"n": "Jaber Al Harthy", "p": 2}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Muhanned Ambusaidi", "p": 3}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Talal Busaidi", "p": 1}, {"n": "Yazan Ambusaidi", "p": 1}]'::jsonb),
  ('Americano 1','social','','[{"n": "Azzan Al Said", "p": 1}, {"n": "Jaber Al Harthy", "p": 4}, {"n": "Laith Al Harthy", "p": 1}, {"n": "Talal Busaidi", "p": 2}, {"n": "Yussuf Al-Harthy", "p": 5}, {"n": "Sultan Al Harthy", "p": 3}]'::jsonb),
  ('Tournament 2','tournament','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Azzan Al Said", "p": 8}, {"n": "Bassam Al Shaidhani", "p": 2}, {"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Mohammed Al Balushi", "p": 2}, {"n": "Muayad Ambusaidi", "p": 10}, {"n": "Muhanned Ambusaidi", "p": 4}, {"n": "Nader Al Qassmi", "p": 1}, {"n": "Salim Al Falahi", "p": 1}, {"n": "Sami Al abdulsalam", "p": 2}, {"n": "Talal Busaidi", "p": 2}, {"n": "Wael Al Barwani", "p": 4}, {"n": "Wael Ambusaidi", "p": 10}, {"n": "Yazan Ambusaidi", "p": 6}, {"n": "Yussuf Al-Harthy", "p": 6}, {"n": "Sultan Al Harthy", "p": 8}]'::jsonb),
  ('Mexicano 2','social','','[{"n": "Abdullah Salim", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Mohd Alhajri", "p": 1}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Muhanned Ambusaidi", "p": 4}, {"n": "Sami Al-busaidi", "p": 2}, {"n": "Wael Ambusaidi", "p": 1}, {"n": "Yazan Ambusaidi", "p": 3}]'::jsonb),
  ('Americano 3','social','','[{"n": "Jaber Al Harthy", "p": 4}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Wael Ambusaidi", "p": 2}, {"n": "Ahmed Al Riyami", "p": 5}, {"n": "Mohd Barwani", "p": 3}, {"n": "Hamdi Al Mawali", "p": 1}]'::jsonb),
  ('Americano 4','social','','[{"n": "Jaber Al Harthy", "p": 1}, {"n": "Mohammed Al Balushi", "p": 1}, {"n": "Nader Al Qassmi", "p": 1}, {"n": "Wael Ambusaidi", "p": 2}, {"n": "Yussuf Al-Harthy", "p": 5}, {"n": "Khaled Al Harthy", "p": 4}, {"n": "Mohd Barwani", "p": 3}]'::jsonb),
  ('Mexicano 3','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Badar Al ghafri", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 3}, {"n": "Mohd Alhajri", "p": 1}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Muhanned Ambusaidi", "p": 4}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Talal Busaidi", "p": 1}, {"n": "Wael Ambusaidi", "p": 2}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Haitham Al Riyami", "p": 1}]'::jsonb),
  ('Americano 5','social','','[{"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Mohd Alhajri", "p": 4}, {"n": "Muayad Ambusaidi", "p": 3}, {"n": "Wael Ambusaidi", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Ahmed Al Riyami", "p": 5}, {"n": "Haitham Al Riyami", "p": 1}, {"n": "Mohd Barwani", "p": 2}]'::jsonb),
  ('Mexicano 4','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 3}, {"n": "Wael Ambusaidi", "p": 4}, {"n": "Yussuf Al-Harthy", "p": 2}, {"n": "Ahmed Al Riyami", "p": 5}, {"n": "Hamdi Al Mawali", "p": 1}]'::jsonb),
  ('Americano 6','social','','[{"n": "Lutfy Al Oweiny", "p": 2}, {"n": "Mohd Alhajri", "p": 4}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Khaled Al Harthy", "p": 1}]'::jsonb),
  ('Americano 7','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Muayad Ambusaidi", "p": 4}, {"n": "Salim Al Falahi", "p": 1}, {"n": "Wael Al Barwani", "p": 2}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Yussuf Al-Harthy", "p": 5}]'::jsonb),
  ('Americano 8','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Asad Al Touqi", "p": 2}, {"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Wael Al Barwani", "p": 4}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Musab Al Siyabi", "p": 4}, {"n": "Mohd Barwani", "p": 5}]'::jsonb),
  ('Americano 9','social','','[{"n": "Asad Al Touqi", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 2}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Khaled Al Harthy", "p": 1}, {"n": "Ahmed Al Azri", "p": 1}]'::jsonb),
  ('Americano 10','social','','[{"n": "Asad Al Touqi", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 3}, {"n": "Muayad Ambusaidi", "p": 5}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Musab Al Siyabi", "p": 4}, {"n": "Khaled Al Harthy", "p": 1}, {"n": "Ahmed Al Azri", "p": 1}, {"n": "Samer", "p": 1}]'::jsonb),
  ('Americano 11','social','','[{"n": "Asad Al Touqi", "p": 2}, {"n": "Salim Al Falahi", "p": 1}, {"n": "Wael Al Barwani", "p": 5}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Ahmed Al Azri", "p": 4}]'::jsonb),
  ('Americano 12','social','','[{"n": "Abdullah Ali", "p": 2}, {"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Mohammed Al Balushi", "p": 1}, {"n": "Wael Al Barwani", "p": 3}, {"n": "Wael Ambusaidi", "p": 1}, {"n": "Musab Al Siyabi", "p": 4}, {"n": "Ahmed Al Azri", "p": 5}]'::jsonb),
  ('Americano 13','social','','[{"n": "Abdullah Ali", "p": 1}, {"n": "Muayad Ambusaidi", "p": 4}, {"n": "Salim Al Falahi", "p": 1}, {"n": "Wael Al Barwani", "p": 2}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Yussuf Al-Harthy", "p": 5}]'::jsonb),
  ('Americano 14','social','','[{"n": "Bassam Al Shaidhani", "p": 3}, {"n": "Salim Al Falahi", "p": 1}, {"n": "Wael Al Barwani", "p": 4}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Ahmed Al Azri", "p": 5}, {"n": "Samer", "p": 1}]'::jsonb),
  ('Americano 15','social','','[{"n": "Badar Al ghafri", "p": 1}, {"n": "Mohd Alhajri", "p": 4}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Wael Ambusaidi", "p": 3}, {"n": "Mohd Barwani", "p": 2}, {"n": "Nasser Al Hajri", "p": 5}]'::jsonb),
  ('Americano 16','social','','[{"n": "Abdullah Salim", "p": 1}, {"n": "Mohd Alhajri", "p": 3}, {"n": "Ahmed Al Riyami", "p": 5}, {"n": "Ahmed Al Azri", "p": 4}, {"n": "Mohsin Al Battashi", "p": 1}, {"n": "Abdul Malik Al Balushi", "p": 2}]'::jsonb),
  ('Americano 17','social','','[{"n": "Azzan Al Said", "p": 1}, {"n": "Lutfy Al Oweiny", "p": 1}, {"n": "Wael Al Barwani", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 5}, {"n": "Ali Al Hajri", "p": 3}, {"n": "Ahmed Al Azri", "p": 2}, {"n": "Mohsin Al Battashi", "p": 1}, {"n": "Abdul Malik Al Balushi", "p": 4}]'::jsonb),
  ('Americano 18','social','','[{"n": "Mohd Alhajri", "p": 1}, {"n": "Wael Ambusaidi", "p": 2}, {"n": "Ali Al Hajri", "p": 5}, {"n": "Ahmed Al Azri", "p": 4}, {"n": "Mohsin Al Battashi", "p": 1}, {"n": "Abdul Malik Al Balushi", "p": 3}]'::jsonb),
  ('Americano 19','social','','[{"n": "Nader Al Qassmi", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 3}, {"n": "Faisal Al Ghailani", "p": 1}, {"n": "Haitham Al Riyami", "p": 2}, {"n": "Mohd Barwani", "p": 4}, {"n": "Mohammed Al Asmi", "p": 5}]'::jsonb),
  ('Americano 20','social','','[{"n": "Mohd Alhajri", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 3}, {"n": "Haitham Al Riyami", "p": 2}, {"n": "Ahmed Al Azri", "p": 4}, {"n": "Mohsin Al Battashi", "p": 5}, {"n": "Asaad Al Dhuhli", "p": 1}]'::jsonb),
  ('Mexicano 5','social','','[{"n": "Sami Al-busaidi", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 2}, {"n": "Ali Al Hajri", "p": 4}, {"n": "Faisal Al Ghailani", "p": 1}, {"n": "Mohd Barwani", "p": 1}, {"n": "Ahmed Al Azri", "p": 1}, {"n": "Mohsin Al Battashi", "p": 3}, {"n": "Sultan B", "p": 5}]'::jsonb),
  ('Americano 21','social','','[{"n": "Sami Al-busaidi", "p": 2}, {"n": "Yussuf Al-Harthy", "p": 1}, {"n": "Faisal Al Ghailani", "p": 4}, {"n": "Haitham Al Riyami", "p": 1}, {"n": "Ahmed Al Azri", "p": 5}, {"n": "Abdul Malik Al Balushi", "p": 3}, {"n": "Amir", "p": 4}, {"n": "Mohammed Saud", "p": 1}, {"n": "Sultan Al Harthy", "p": 1}]'::jsonb),
  ('Tournament 2 (b)','tournament','','[{"n": "Asad Al Touqi", "p": 4}, {"n": "Mohd Alhajri", "p": 1}, {"n": "Muayad Ambusaidi", "p": 18}, {"n": "Sami Al-busaidi", "p": 1}, {"n": "Yussuf Al-Harthy", "p": 7}, {"n": "Ali Al Hajri", "p": 13}, {"n": "Musab Al Siyabi", "p": 7}, {"n": "Ahmed Al Azri", "p": 17}, {"n": "Asaad Al Dhuhli", "p": 1}, {"n": "Sultan Al Harthy", "p": 5}, {"n": "Haitham", "p": 15}, {"n": "Sulaiman", "p": 1}]'::jsonb),
  ('Americano 22','social','','[{"n": "Ahmed Al Azri", "p": 5}]'::jsonb),
  ('Americano 23','social','','[{"n": "Wael Ambusaidi", "p": 2}, {"n": "Yussuf Al-Harthy", "p": 4}, {"n": "Faisal Al Ghailani", "p": 1}, {"n": "Haitham Al Riyami", "p": 1}, {"n": "Mohd Barwani", "p": 3}, {"n": "Mohammed Al Asmi", "p": 5}]'::jsonb),
  ('Americano 24','social','','[{"n": "Mohd Alhajri", "p": 2}, {"n": "Wael Ambusaidi", "p": 5}, {"n": "Faisal Al Ghailani", "p": 3}, {"n": "Mohd Barwani", "p": 4}, {"n": "Asaad Al Dhuhli", "p": 1}, {"n": "Yussuf Al Barwani", "p": 1}]'::jsonb),
  ('Americano 25','social','','[{"n": "Azzan Al Said", "p": 4}, {"n": "Wael Ambusaidi", "p": 1}, {"n": "Ali Al Hajri", "p": 5}, {"n": "Ahmed Al Riyami", "p": 3}, {"n": "Haitham Al Riyami", "p": 1}, {"n": "Mohd Barwani", "p": 1}, {"n": "Abdul Malik Al Balushi", "p": 1}, {"n": "Yussuf Al Barwani", "p": 2}]'::jsonb),
  ('Americano 26','social','','[{"n": "Mohd Alhajri", "p": 5}, {"n": "Wael Ambusaidi", "p": 4}, {"n": "Yussuf Al-Harthy", "p": 3}, {"n": "Mohd Barwani", "p": 2}, {"n": "Abdul Malik Al Balushi", "p": 5}, {"n": "Yussuf Al Barwani", "p": 1}]'::jsonb);
